name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.7, 3.0, 3.1, 3.2]

    services:
      mysql:
        image: mysql:8.0
        env:
          ALLOW_EMPTY_PASSWORD: yes

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.bundle
        key: ${{ runner.os }}-ruby-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-ruby-${{ matrix.ruby-version }}-
          ${{ runner.os }}-ruby-

    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h mysql --silent; do
          echo 'Waiting for MySQL to start...'
          sleep 1
        done

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      env:
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
        MYSQL_SOCKET: /var/run/mysqld/mysqld.sock
      run: bundle exec rake
