name: CI

on: [push, pull_request]

env:
  RAILS_ENV: test
  RACK_ENV: test
  MYSQL_HOST: 127.0.0.1
  MYSQL_PORT: 3306

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.7, 3.0, 3.1, 3.2]

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.bundle
        key: ${{ runner.os }}-ruby-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-ruby-${{ matrix.ruby-version }}-
          ${{ runner.os }}-ruby-

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Prepare database
      run: |
        bundle exec rake db:create
        bundle exec rake db:migrate

    - name: Run tests
      env:
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
      run: bundle exec rake
